In [2]:
import pandas as pd
import numpy as np

In [6]:
pd.Series(np.arange(10))

0    0
1    1
2    2
3    3
4    4
5    5
6    6
7    7
8    8
9    9
dtype: int64

# 2. DataFrame

例子1：

In [12]:
np.random.randn(2,3) # 从标准正态分布中返回一个或多个样本值 2行3列

array([[-1.34517925,  2.62682241,  0.08795299],
       [ 0.74685993, -0.97215403,  0.24361227]])

In [13]:
pd.DataFrame(np.random.randn(2,3)) 

0         1         2
0 -1.017791  0.987338 -1.216922
1 -0.077990 -0.919915 -0.670458

例子2：

In [3]:
# 构造学生分数
score = np.random.randint(40,100,(10,5))

In [4]:
score

array([[84, 71, 89, 74, 99],
       [53, 88, 50, 95, 46],
       [95, 49, 66, 97, 65],
       [92, 96, 56, 69, 55],
       [49, 88, 41, 80, 56],
       [71, 95, 96, 80, 84],
       [49, 77, 87, 85, 59],
       [91, 63, 98, 68, 58],
       [46, 99, 93, 76, 66],
       [44, 97, 93, 62, 45]], dtype=int32)

In [6]:
# 转化为pandas中的数据结构
score_df = pd.DataFrame(score)

In [7]:
score_df

0   1   2   3   4
0  84  71  89  74  99
1  53  88  50  95  46
2  95  49  66  97  65
3  92  96  56  69  55
4  49  88  41  80  56
5  71  95  96  80  84
6  49  77  87  85  59
7  91  63  98  68  58
8  46  99  93  76  66
9  44  97  93  62  45

In [16]:
# 构造行 列索引
subjects = ["语文", "数学", "英语", "政治", "体育"]
stu = ["同学"+str(i) for i in range(score_df.shape[0])]

# 生成带行列索引的DadaFrame数据结构
data = pd.DataFrame(score, columns=subjects, index=stu)

In [17]:
data

语文  数学  英语  政治  体育
同学0  84  71  89  74  99
同学1  53  88  50  95  46
同学2  95  49  66  97  65
同学3  92  96  56  69  55
同学4  49  88  41  80  56
同学5  71  95  96  80  84
同学6  49  77  87  85  59
同学7  91  63  98  68  58
同学8  46  99  93  76  66
同学9  44  97  93  62  45

In [15]:
score_df.shape

(10, 5)

## 2.1 DataFrame的属性

In [26]:
data.shape

(10, 5)

In [18]:
data.head(5)

语文  数学  英语  政治  体育
同学0  84  71  89  74  99
同学1  53  88  50  95  46
同学2  95  49  66  97  65
同学3  92  96  56  69  55
同学4  49  88  41  80  56

In [19]:
data.tail(5)

语文  数学  英语  政治  体育
同学5  71  95  96  80  84
同学6  49  77  87  85  59
同学7  91  63  98  68  58
同学8  46  99  93  76  66
同学9  44  97  93  62  45

In [20]:
data.index

Index(['同学0', '同学1', '同学2', '同学3', '同学4', '同学5', '同学6', '同学7', '同学8', '同学9'], dtype='object')

In [22]:
data.columns

Index(['语文', '数学', '英语', '政治', '体育'], dtype='object')

In [25]:
data.values

array([[84, 71, 89, 74, 99],
       [53, 88, 50, 95, 46],
       [95, 49, 66, 97, 65],
       [92, 96, 56, 69, 55],
       [49, 88, 41, 80, 56],
       [71, 95, 96, 80, 84],
       [49, 77, 87, 85, 59],
       [91, 63, 98, 68, 58],
       [46, 99, 93, 76, 66],
       [44, 97, 93, 62, 45]], dtype=int32)

### 2.1.1 索引的修改
不能对某个索引进行修改，必须批量修改

In [31]:
stu = ["同学_"+str(i) for i in range(score_df.shape[0])]
data.index = stu

In [29]:
stu

['同学_0',
 '同学_1',
 '同学_2',
 '同学_3',
 '同学_4',
 '同学_5',
 '同学_6',
 '同学_7',
 '同学_8',
 '同学_9']

In [32]:
data

语文  数学  英语  政治  体育
同学_0  84  71  89  74  99
同学_1  53  88  50  95  46
同学_2  95  49  66  97  65
同学_3  92  96  56  69  55
同学_4  49  88  41  80  56
同学_5  71  95  96  80  84
同学_6  49  77  87  85  59
同学_7  91  63  98  68  58
同学_8  46  99  93  76  66
同学_9  44  97  93  62  45

### 2.1.2 重设索引

In [33]:
# 重设索引
data.reset_index()

index  语文  数学  英语  政治  体育
0  同学_0  84  71  89  74  99
1  同学_1  53  88  50  95  46
2  同学_2  95  49  66  97  65
3  同学_3  92  96  56  69  55
4  同学_4  49  88  41  80  56
5  同学_5  71  95  96  80  84
6  同学_6  49  77  87  85  59
7  同学_7  91  63  98  68  58
8  同学_8  46  99  93  76  66
9  同学_9  44  97  93  62  45

In [34]:
data.reset_index(drop=True)

语文  数学  英语  政治  体育
0  84  71  89  74  99
1  53  88  50  95  46
2  95  49  66  97  65
3  92  96  56  69  55
4  49  88  41  80  56
5  71  95  96  80  84
6  49  77  87  85  59
7  91  63  98  68  58
8  46  99  93  76  66
9  44  97  93  62  45

### 2.1.3 设置多列为新的索引

In [36]:
df = pd.DataFrame({'month': [1, 4, 7, 10],
                    'year': [2012, 2014, 2013, 2014],
                    'sale':[55, 40, 84, 31]})

In [37]:
df

month  year  sale
0      1  2012    55
1      4  2014    40
2      7  2013    84
3     10  2014    31

In [38]:
df.set_index("year")

month  sale
year             
2012      1    55
2014      4    40
2013      7    84
2014     10    31

In [49]:
df = df.set_index(["year","month"])

多个索引就是MultiIndex多级索引（层次化索引），是一种三维数据的结构

# MultiIndex与Panel
## MultiIndex

In [50]:
df

sale
year month      
2012 1        55
2014 4        40
2013 7        84
2014 10       31

In [51]:
df.index

MultiIndex([(2012,  1),
            (2014,  4),
            (2013,  7),
            (2014, 10)],
           names=['year', 'month'])

In [52]:
df.index.names

FrozenList(['year', 'month'])

In [53]:
df.index.levels

FrozenList([[2012, 2013, 2014], [1, 4, 7, 10]])

In [60]:
df.index.codes # 新版有原来的labels改为codes 详看官方文档

FrozenList([[0, 2, 1, 2], [0, 1, 2, 3]])

## MultiIndex的创建

In [56]:
arrays = [[1,1,2,2], ["r", "b", "r", "b"]]
pd.MultiIndex.from_arrays(arrays, names=["num","col"])

MultiIndex([(1, 'r'),
            (1, 'b'),
            (2, 'r'),
            (2, 'b')],
           names=['num', 'col'])